// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJZcV_Tl4kWSd58MkSGsGRF_JzQRO42o',
    appId: '1:775390620777:web:ae59ef60d3cfceefebc6f8',
    messagingSenderId: '775390620777',
    projectId: 'collector-app-702b0',
    authDomain: 'collector-app-702b0.firebaseapp.com',
    storageBucket: 'collector-app-702b0.firebasestorage.app',
    measurementId: 'G-JLSGRYWL2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQaxolcKcEGXHcuoMoSGqYY8rdsi6ZrI',
    appId: '1:775390620777:android:e06e61de704855c2ebc6f8',
    messagingSenderId: '775390620777',
    projectId: 'collector-app-702b0',
    storageBucket: 'collector-app-702b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEdGkNWp3L2q30rnNASACnDlobM8kEQo',
    appId: '1:775390620777:ios:d538a6ba56eb84d7ebc6f8',
    messagingSenderId: '775390620777',
    projectId: 'collector-app-702b0',
    storageBucket: 'collector-app-702b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEdGkNWp3L2q30rnNASACnDlobM8kEQo',
    appId: '1:775390620777:ios:d538a6ba56eb84d7ebc6f8',
    messagingSenderId: '775390620777',
    projectId: 'collector-app-702b0',
    storageBucket: 'collector-app-702b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiJZcV_Tl4kWSd58MkSGsGRF_JzQRO42o',
    appId: '1:775390620777:web:72e817b9db7e0354ebc6f8',
    messagingSenderId: '775390620777',
    projectId: 'collector-app-702b0',
    authDomain: 'collector-app-702b0.firebaseapp.com',
    storageBucket: 'collector-app-702b0.firebasestorage.app',
    measurementId: 'G-XP91LT71VX',
  );
}
